language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jimkirby/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jimkirby/react-test npm test -- --coverage

after_success:
  - docker build -t jimkirby/multi-client ./client
  - docker build -t jimkirby/multi-nginx ./nginx
  - docker build -t jimkirby/multi-server ./server
  - docker build -t jimkirby/multi-worker ./worker
